### ISSUE TITLE
Generic algorithm names

### ISSUE THREAD

**Issue by YingboMa** [SciML/OrdinaryDiffEq.jl#1172]
We can introduce a few generic algorithm names to OrdinaryDiffEq that decouples the feature of the integrator from the specific algorithm name. This can greatly improve the discoverability of an algorithm. Like MATLAB's `ode45` and `ode23s`, the user can easily tell the former is a high order integrator for non-stiff problems and the latter is a low order integrator for stiff problems.

However, our algorithm names are rather obscure in comparison. For someone that's not in the field, `Rosenbrock23`, `KenCarp4` and `KenCarp5` mean very little. Maybe a user will try to type `BDF` and tab-complete in order to find stiff algorithms, but there won't be any suggestions, because we have `QNDF{s}`, `QBDF{s}`, and `ABDF2`.

I propose the following nomenclature:
```
ODE{order}{_adaptiveorder}{S(L-stable or B-stable)/A(A-stable or A(alpha)-stable)}{I(fully implicit)}{L(suitable for large problems)}
```
E.g., `Tsit5 <=> ODE5`. `Rosenbrock23 <=> ODE2S`. `TRBDF2 <=> ODE2SL`, `QNDF <=> ODE1_5S` (or `ODE1_5A` or `ODE1_5SA`), `DImplicitEuler <=> ODE1SI`.

Specialized methods like split algorithms, SSP RKs, and low-storage methods may deserve their own name.

CC: @ChrisRackauckas @devmotion

**Comment by devmotion** [comment]
Yeah, I agree, due to the large amount of algorithms it can be quite difficult for users to figure out which one might be suitable even if they know that they are dealing with a stiff problem.

Unfortunately, I guess we can only provide more descriptive aliases for a subset of algorithms because they will clash at some point. I still think it might be useful for the common/recommended methods though.

Additionally, one could maybe add helper methods for retrieving the set of all algorithms of a specific order, stability, etc.

**Comment by ChrisRackauckas** [comment]
Possibly, or it might add confusion.
