### ISSUE TITLE
Stiffness detection fails when autodiff=false

### ISSUE THREAD

**Issue by andreasnoack** [SciML/OrdinaryDiffEq.jl#1260]
It works when setting `autodiff=true` and both Sundials and LSODA seem to be able to handle the problem so maybe something about the finite difference derivative would have to be handled differently.

With
```julia
using OrdinaryDiffEq, Sundials, LSODA

_pre = t -> begin
    a1  = 1415.1793182451613
    a2  = 5.0
    a3  = 35.81269190566677
    a4  = 90.0
    a5  = 47.0
    a6  = 0.53
    a7  = 14207.185127863131
    a8  = 0.2308591023668783
    a9  = 5.0
    a10 = 1.0151271017737353e6
    a11 = a4*a10
    a12 = 8.64e8
    a13 = 0.03300701
    a14 = 1.5291827538503767e-5
    a15 = 0.0008460637315723219
    a16 = 0.011598929410558527
    a17 = 0.005
    a18 = 0.14524610170788177
    a19 = 57.001
    a20 = 169.001
    a21 = 0.7273
    a22 = 0.2308591023668783
    a23 = 6.196531015647886e11
    a24 = (a23 * ((a5/35)^a18))
    a25 = a4 * a1 * (exp((-(t - a2)^2)/(2*(a3^2))))
    a26 = a4 * a1 * (exp((-(t - (a2 + a19))^2)/(2*(a3^2))))
    a27 = a4 * a1 * (exp((-(t - (a2 + a20))^2)/(2*(a3^2))))
    b1  = a21 * ((t < (a19 + a9)) & (t > a19)) + zero(a21)
    b2  = a21 * ((t < (a20 + a9)) & (t > a20)) + zero(a21)
    c1  = a22 * !(t < (a19 + a9)) + zero(a22)
    c2  = a22 * !(t < (a20 + a9)) + zero(a22)
    return (
        a6=a6, a7=a7, a8=a8, a11=a11,
        a12=a12, a13=a13, a14=a14,
        a15=a15, a16=a16, a17=a17,
        a25=a25, a26=a26, a27=a27,
        b1=b1, b2=b2, c1=c1, c2=c2
    )
end

_prob = ODEProblem(
    (du, u, _p, t) -> begin
        p = _p(t)
        du[1]  = p.a25 - (0.55*p.a6 + p.a7)*u[1] - p.a14*u[1]
        du[2]  = 0.55*p.a6*u[1] - (p.c1 + p.a8)*u[2] + p.b1*u[2]*log(p.a11/(abs(u[2]) + 1e-6))
        du[3]  = p.a26 + p.c1*u[2] - (0.55*p.a6 + p.a7)*u[3] - p.a15*u[3]
        du[4]  = 0.55*p.a6*u[3] - (p.c2 + p.a8)*u[4] + p.b2*u[4]*log(p.a11/(abs(u[4]) + 1e-6))
        du[5]  = p.a27 + p.c2*u[4] - (0.55*p.a6 + p.a7)*u[5] - p.a16*u[5]
        du[6]  = 0.55*p.a6*u[5] - p.a8*u[6]
        du[7]  = 0.44*p.a12*(u[1] + u[3] + u[5]) + p.a12*(u[8]+u[9]+u[10])- p.a13*u[7]
        du[8]  = p.a14*u[1] - p.a17*u[8]
        du[9]  = p.a15*u[3] - p.a17*u[9]
        du[10] = p.a16*u[5] - p.a17*u[10]
    end,
    zeros(10),
    (0.0, 300),
    _pre
)
```
I'm getting
```julia
julia> solve(_prob, AutoVern7(Rodas5(autodiff=false)), abstol=1e-6, reltol=1e-6);
┌ Warning: Interrupted. Larger maxiters is needed.
└ @ DiffEqBase ~/.julia/packages/DiffEqBase/kRzKx/src/integrator_interface.jl:329

julia> solve(_prob, AutoVern7(Rodas5()), abstol=1e-6, reltol=1e-6); # OK

julia> solve(_prob, CVODE_BDF(), abstol=1e-6, reltol=1e-6); # OK

julia> solve(_prob, lsoda(), abstol=1e-6, reltol=1e-6); # OK
```

**Comment by ChrisRackauckas** [comment]
```julia
solve(_prob, AutoVern7(Rodas5(autodiff=false,diff_type=Val{:central})), abstol=1e-6, reltol=1e-6)
```

works fine, so this is directly due to the error in the Jacobian approximation in finite differencing. The scale difference is:

```
a23 = 6.196531015647886e11
a14 = 1.5291827538503767e-5
```

just barely within 64-bit floating point representation, so I'm actually surprised central differencing is fine. Anyways, this is a case where a non-W Rosenbrock simply requires autodiff.

**Comment by andreasnoack** [comment]
This is a reduced version of a larger problem and I just realized that the variables with the largest magnitudes aren't used so I've now updated the example.

I'm curious why LSODA and Sundials don't have problems here.

**Comment by ChrisRackauckas** [comment]
Because those aren't Rosenbrock methods. Implicit equations don't need an accurate Jacobian for Newton's method to converge: it just needs to be "close". LSODA and Sundials get a little bit lucky here, for the same reason that TRBDF2, KenCarp4, RadauIIA5, etc. all get lucky because the Newton method still seems to converge, albeit at a low convergence rate.

For Rosenbrock methods, there's no implicit system, but the accuracy of the Jacobian factors into the error calculation. So Rosenbrock methods have a chance of just directly failing if the Jacobian calculation is too far off, while implicit methods can be more robust but would slow down.

Anyways, the solution on this type of problem is symbolic or automatic differentiation for sure. Rodas with an accurate Jacobian is what you want, or adaptive Radau.
