### ISSUE TITLE
stage_limiter! and step_limiter! for SSPRK methods should get p as argument

### ISSUE THREAD

**Issue by ranocha** [SciML/OrdinaryDiffEq.jl#1285]
Right now, the `stage_limiter!` and `step_limiter!` of SSPRK methods are called as
```julia
  stage_limiter!(u, f, t+dt)
  step_limiter!(u, f, t+dt)
```
It would be far more convenient if they also received the parameters `p` as additional argument, e.g.
```julia
  stage_limiter!(u, f, p, t+dt)
  step_limiter!(u, f, p, t+dt)
```
If I remember correctly, these limiters were introduced before parameters were handled explicitly in the DiffEq ecosystem. Hence, it seems natural to pass parameters explicitly now.

Technically, this would be a breaking change. However, I doubt many people use this infrastructure right now. However, we want to make use of it in Trixi.jl.

**Comment by ranocha** [comment]
I am of course willing to implement this change in OrdinaryDiffEq. However, I would like to get some feedback first whether this would be accepted at all or whether there is another option.

**Comment by ChrisRackauckas** [comment]
I'd say, just go for it. It's my fault that I forgot to update these, so I'd call it a bug. Changing the function syntax will throw an error, so it's not the worst thing ever since users will essentially be notified about the change. If you want to make the first call to it a try/catch to throw a better error message, then I think that's 110% the solution. But yes, let's just move this forward.

**Comment by ranocha** [comment]
Okay, I'll do that.
