### ISSUE TITLE
GMRES losing order of convergence on IterativeSolvers v0.9

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/OrdinaryDiffEq.jl#1316]
Found in https://github.com/SciML/OrdinaryDiffEq.jl/pull/1315 . Reproducer

```julia
using OrdinaryDiffEq

μ = 1.01
u0 = rand(2)
A = [2.0 -1.0; -1.0 2.0]
linnonlin_f1 = DiffEqArrayOperator(A)
linnonlin_f2 = (du,u,p,t) -> du .= μ .* u
linnonlin_fun_iip = SplitFunction(linnonlin_f1,linnonlin_f2;analytic=(u0,p,t)->exp((A+μ*I)*t)*u0)
prob = SplitODEProblem(linnonlin_fun_iip,u0,(0.0,1.0))

dts = 1 ./2 .^(14:-1:10) #14->7 good plot
Alg = KenCarp3(linsolve=LinSolveGMRES(abstol=1e-16,reltol=1e-16))
sim  = test_convergence(dts,prob,Alg)

using Plots
plot(sim)
```

![plot](https://user-images.githubusercontent.com/1814174/103434130-e147fb00-4bca-11eb-8619-c564a937f833.png)

Perfect... second order convergence? @YingboMa could you look into what might've happened here?

**Comment by YingboMa** [comment]
It works for me
```julia
julia> sim.𝒪est
Dict{Any, Any} with 3 entries:
  :l∞    => 3.00689
  :final => 3.00982
  :l2    => 3.01503
```

**Comment by YingboMa** [comment]
Since we are forwarding the reltol to the linear solver, we need to set the `reltol` low when doing convergence rate calculation, i.e.:

```julia
julia> sim = test_convergence(dts,prob,Alg); sim.𝒪est
Dict{Any, Any} with 3 entries:
  :l∞    => 2.00158
  :final => 2.00175
  :l2    => 2.00214

julia> sim = test_convergence(dts,prob,Alg,reltol=1e-16); sim.𝒪est
Dict{Any, Any} with 3 entries:
  :l∞    => 3.00551
  :final => 3.00624
  :l2    => 3.00941
```

**Comment by ChrisRackauckas** [comment]
Interesting, but it always forwarded reltol?

**Comment by YingboMa** [comment]
I think we should remove the forwarding in https://github.com/SciML/OrdinaryDiffEq.jl/commit/8d6dfdd4eedb5826bd26ddf6adaeb6ea821d576a#diff-ff840b6abcb9fc49f06fd47579e49eb1c845dc3b9a8db0f397206649cd4187d6R157 because that's not always valid, since `integrator.opts.reltol` could be a vector. Then, because of precedence https://github.com/SciML/DiffEqBase.jl/blob/master/src/linear_nonlinear.jl#L164 the `kwargs` from the Newton always override the tolerance setting in `LinSolveGMRES(abstol=1e-16,reltol=1e-16)`

**Comment by ChrisRackauckas** [comment]
We should at least flip the precedence of the kwarg splatting. What about only forwarding that if adaptive=true?

**Comment by ChrisRackauckas** [comment]
Reopening this to change the OrdinaryDiffEq side. DiffEqBase side should be merged.
