### ISSUE TITLE
Problem with set_proposed_dt! inside DiscreteCallBack

### ISSUE THREAD

**Issue by mleprovost** [SciML/OrdinaryDiffEq.jl#1351]
Hello,

I would like to change the time step  of the solver into a DiscreteCallBack using `set_proposed_dt!(integrator,0.5)`, the CallBack is working but the time step is not changed.  I also tried `integrator.dt = 0.5` in `affect!`.
Here is a code to  reproduce the error:
I do a DiscreteCallBack when the state is below 0, which modifies the time step of the integrator. The callback is activated at the 12th step.
```
using DifferentialEquations
using OrdinaryDiffEq

function f(du,u,p,t)
    if p == 0
  du[1] = -1.0
    else
  du[1] = 1.0
    end
end
p = 0

 function condition(u,t,integrator) # Switch model if u[1]<0.0
  u[1]<0.0
end
function affect!(integrator)
  integrator.p = 1
  set_proposed_dt!(integrator,0.5)
end
cb = DiscreteCallback(condition,affect!;save_positions=(false,true))

u0 = [1.0]
tspan = (0.0,5.0)
prob = ODEProblem(f,u0,tspan,p)

sol = solve(prob,RK4(), dt = 0.1,adaptive = false, callback=cb)

plot(sol.t,sol[1,:])
sol.u[12]
sol.t[10:15]
```

Thank you for your help,

**Comment by fabern** [comment]
> set_proposed_dt! in OrdinaryDiffEq should probably change both values then.

Modifying both values would work for `set_proposed_dt!`. But `get_proposed_dt` should still return only one value.

One could use the switch `integrator.opts.adaptive` to modify/return the correct value. 
Or non-adaptive solvers could be modified to use `integrator.dtpropose` instead of `integrator.dtcache`?

------
Relavant code:

https://github.com/SciML/StochasticDelayDiffEq.jl/blob/25524178668e5b40bb74417dfc0773ca03d564ab/src/integrators/interface.jl#L248-L254

https://github.com/SciML/StochasticDiffEq.jl/blob/f576a5e9cd89d8cf36f242a275ded500619feef3/src/integrators/integrator_interface.jl#L36-L44

https://github.com/SciML/OrdinaryDiffEq.jl/blob/69484227aa2b069d42f2c269339c84e34bbfa127/src/integrators/integrator_interface.jl#L51-L59

**Comment by ChrisRackauckas** [comment]
I think they both need to change. See https://github.com/SciML/OrdinaryDiffEq.jl/pull/1352 .
