### ISSUE TITLE
Interpolation of LinearExponential<:AbstractDiffEqOperator is not working right

### ISSUE THREAD

**Issue by aelmokadem** [SciML/OrdinaryDiffEq.jl#1491]
@freemin7

I have been trying to compare the solutions from the numeric ODE solver and the linear exponential solver for a very simple example and the results are very different. Setting a fixed `dt` fixes the problem which points to a bad interpolation with `LinearExponential` !

Thank you.

The code:
```
# solve with numeric ODE solver
function ode!(du, u, p, t)
  du[1] = -0.1*u[1]
  du[2] = 0.1*u[1] - 2.5*u[2]
end

u0 = [320.0, 0.0]
tspan = (0.0, 25.0)

prob = ODEProblem(ode!, u0, tspan)
sol = solve(prob, Tsit5(), saveat=0.1) 
Plots.plot(sol)

# solve with linear exponential solver
A_ = [-0.1 0.0; 0.1 -2.5]
A = DiffEqArrayOperator(A_)
prob_lin = ODEProblem(A, u0, tspan)
sol_lin = solve(prob_lin, LinearExponential(), saveat=0.1) 
Plots.plot(sol_lin)
```

Results:
Numeric ODE solver:
<img width="480" alt="Screen Shot 2021-09-05 at 8 49 59 AM" src="https://user-images.githubusercontent.com/31896854/132127458-ec97cf72-b1ca-4911-a467-e927b88e3f52.png">

Linear exponential solver:
<img width="476" alt="Screen Shot 2021-09-05 at 8 50 09 AM" src="https://user-images.githubusercontent.com/31896854/132127470-246ded21-2171-446d-8354-dd3d2c5606ee.png">

Linear exponential with fixed dt
<img width="461" alt="Screen Shot 2021-09-07 at 8 21 03 AM" src="https://user-images.githubusercontent.com/31896854/132344601-89041f27-302d-4be7-9174-6cceb1c48883.png">

**Comment by aelmokadem** [comment]
Thanks @ChrisRackauckas

**Comment by freemin7** [comment]
@ChrisRackauckas How much eco system wide plumbing would be necessary to  associate certain solvers with their own interpolation?

**Comment by ChrisRackauckas** [comment]
Most solvers have their own interpolation (Tsit5, all Verners, etc.). That's not the issue. The issue is that LinearExponential does not have a good interpolation scheme in general. It calculates the analytical solution at some time in the future no matter far. Any interpolation has error, so it won't have guarantees. That is unless the interpolation is just another exponentiation, which would be extremely expensive since it would cost as much as the step itself, which is not a property you generally see with interpolations (usually they are free or close to free). One could define a scheme where it iteratively adds new points until the interpolation is globally below some error threshold (measuring it how?), but that again would be expensive because 1 exponentiation now became N, so you better be sure the user actually wants N points. So I think the best thing here is, if you want the analytical solution at N points, you just use `tstops` to say that and we make sure that's documented.

**Comment by freemin7** [comment]
While agree that solving (a step) is a expensive as calling an interpolation (querying the exponential) that is only because the solving is incredibly cheap. (At least for time invariant system)

And I see multiple techniques that involve caching to reuse new information gained during interpolation however I agree that coming up with a scheme that works well in all cases is likely going to be an actual research effort.

I am fine with it's current state (the behaviour being documented) if any have insights  I might revisit this.

**Comment by ChrisRackauckas** [comment]
I think the right way to do it would be a higher order Hermite interpolation, generated by solving at the Gauss points (which should converge the fastest). Then you could probably use the same Gauss-Kronrod rules to check the global accuracy, and keep adding points similar to a quadrature until the interpolation is blow the tolerance in a global sense. That seems more like a GlobalDiffEq.jl idea, and would be a very interesting method IMO.
