### ISSUE TITLE
Ralston's method has the wrong coefficients

### ISSUE THREAD

**Issue by patrick-kidger** [SciML/OrdinaryDiffEq.jl#1592]
So Ralston's method is the 2/3-method, not the 3/4-method:

![image](https://user-images.githubusercontent.com/33688385/152335400-0ee8aff6-fdb2-4069-b10d-72ee6d552845.png)

(Although as you can see it does use 3/4 elsewhere, which is the probable source of the confusion.)

OrdinaryDiffEq.jl currently implements it as the 3/4 method.

https://github.com/SciML/OrdinaryDiffEq.jl/blob/d1bacc9dc6d6d7ad070444b65d5415efa761345c/src/perform_step/fixed_timestep_perform_step.jl#L106
https://github.com/SciML/OrdinaryDiffEq.jl/blob/d1bacc9dc6d6d7ad070444b65d5415efa761345c/src/perform_step/fixed_timestep_perform_step.jl#L112

---

FWIW I've seen this mistake restated elsewhere on the internet, and in fact it looks like Wikipedia had this wrong for a while. My guess is that someone wrote the wrong thing on Wikipedia at some point, and the rest of the world blindly copied it!

**Comment by ChrisRackauckas** [comment]
"Clearly" and then controversy. Classic 😆. Yeah I pulled from Wikipedia because surely the simple methods should be right, right? Look at Bogacki-Shampine: 

https://en.wikipedia.org/wiki/Bogacki%E2%80%93Shampine_method
https://www.sciencedirect.com/science/article/pii/0893965989900797?via%3Dihub

They pulled the tableau from Ralston but from his book:

https://www.thriftbooks.com/w/a-first-course-in-numerical-analysis_anthony-ralston_philip-rabinowitz/1266780/item/44512233/?gclid=CjwKCAiAl-6PBhBCEiwAc2GOVJdWmbJ82GQ7hI61hPBrhC92D42TsKtt0e9XyX0irrGEnWloFZmwIRoCg8oQAvD_BwE#idiq=44512233&edition=47372714

<img width="436" alt="Screenshot 2022-02-03 072934" src="https://user-images.githubusercontent.com/1814174/152343038-1bc086ff-77b9-40a3-ac51-2e497afaf6a9.png">

But that's 3rd order, and has the 3/4. The second order above it:

<img width="436" alt="Screenshot 2022-02-03 072934" src="https://user-images.githubusercontent.com/1814174/152344225-71f024c0-fe76-4eb4-b88e-1252bd1dc0b4.png">

So yeah, I think I see the source of confusion. The Bogacki-Shampine work points to the 3rd order method and says it's evaluated at the 3/4, and then the 2nd order method is evaluated at the 2/3 but then has b2=3/4, so someone along the way looked at both and flipped that to a2=3/4, and it turns out a2=3/4, b1=1/3, b2=2/3 is still a valid second order method and slipped under the radar?

Amazing. Yeah we should get that fixed.

**Comment by patrick-kidger** [comment]
Haha yeah, this was a fun observation. Credit to my colleague James Foster for insisting that "no really, Ralston is 2/3" over my objections that OrdinaryDiffEq.jl, Wikipedia, and the rest of the internet stated it was the 3/4-method.
