### ISSUE TITLE
ROCK algorithms fail to initialize when part of a composite algorithm

### ISSUE THREAD

**Issue by danielwe** [SciML/OrdinaryDiffEq.jl#1618]
AutoDP5(ROCK4()) errors out at the following line when it switches to  ROCK4:

https://github.com/SciML/OrdinaryDiffEq.jl/blob/79ba28b6ff19e8424fb5926485bb90ab631b0ebd/src/perform_step/rkc_perform_step.jl#L267

Here, `integrator.alg` points to the CompositeAlgorithm instance, not the ROCK4 instance, so it doesn't have a `max_stages` field. Glancing through the rest of the file, the issue also affects ROCK2, and more generally I guess any algorithm that references `integrator.alg` may fail to work as part of a CompositeAlgorithm.

**Comment by danielwe** [comment]
I guess the least invasive solution would be to do something like

```julia
alg = (integrator.alg isa CompositeAlgorithm) ? integrator.alg.algs[current] : integrator.alg
```

in each of the affected functions, and then proceed using `alg`. The problem is that the `current` index is stored on the CompositeCache, which is not passed to these functions, so a slight redesign is needed one way or the other.

**Comment by ChrisRackauckas** [comment]
there's an internal function `_unwrap_alg(alg)` for this. We just need to use it here. BTW, what's the use case for this? Since ROCK is already an explicit algorithm, I would assume that this wouldn't do much?

**Comment by danielwe** [comment]
Aha, should have noticed that. (Please excuse my earlier musings then.)

And yeah, I guess I had that question myself. ROCK4 and the other stabilized explicit methods are listed among the methods for stiff equations in the docs, so I figured I'd try this in my experimentation/benchmarking even though I think I was somewhat aware of the association between stiff equations and implicit methods. Is this a documentation bug?

**Comment by danielwe** [comment]
Speaking of documentation bugs, there is no SERK2v2, only SERK2. Separate issue perhaps.

**Comment by ChrisRackauckas** [comment]
It's not a documentation bug. "the association between stiff equations and implicit methods" is just wrong. There are many non-implicit methods for stiff equations (exponential integrators, ROCK methods, etc.), and there are also implicit methods for non-stiff equations (LSODA/LSODE/VODE/CVODE's Adam's method is Adams-Bashforth-Moulton, implicit, and one of the most used non-stiff ODE solvers ever!). ROCK methods are explicit Runge-Kutta methods designed for specific kinds of stiff equations, and in some cases they benchmark as the fastest method. See https://benchmarks.sciml.ai/html/MOLPDE/Filament.html. They adapt the number of stages they used based on the stiffness of the equation. Because of that, I'm skeptical that combining it with another RK method makes sense, but hey, every combination probably has a use for something.

>Speaking of documentation bugs, there is no SERK2v2, only SERK2. Separate issue perhaps.

Oh nice catch. Yeah that would be worth adding.

**Comment by danielwe** [comment]
> "the association between stiff equations and implicit methods" is just wrong.

Oops, retreating again. It's hard being a dilettante. I did do a numerical analysis course way back, but these days ODE integration is a tool and not my expertise, which is why it's so great to have a library that just lets you try and benchmark lots of different algorithms with adaptive timestepping and autoswitching.

**Comment by ChrisRackauckas** [comment]
Don't worry, a lot of people teach it so a lot of people thing it. Professors need to make some simplifications when teaching, and this is a rather decent one to make. But it does hide a bit of the true complexity of the space.

**Comment by danielwe** [comment]
> Speaking of documentation bugs, there is no SERK2v2, only SERK2. Separate issue perhaps.

#1621

**Comment by danielwe** [comment]
> Professors need to make some simplifications when teaching, and this is a rather decent one to make.

Profs were great. I had both Kværnø and Owren sub in during my undergrad, though never as principal instructors (Owren even in the mentioned course I think). It's just been a while.

**Comment by danielwe** [comment]
Btw. seems like this line in `dolinsolve` assumes that implicit => stiff, i.e., it assumes that if you're doing a linsolve you're definitely the stiff algorithm:

https://github.com/SciML/OrdinaryDiffEq.jl/blob/2d8fd6500e1be2f0f07e6ac37152aa2f629497e6/src/misc_utils.jl#L93

From what I can tell this is correct at the moment (no non-stiff implicit methods in OrdinaryDiffEq) but doesn't seem like a robust assumption given what you said above.

In general the `is_stiff` argument to `unwrap_alg` seems redundant and requires functions like `dolinsolve` to make assumptions about their calling context, not to mention it trusts that people aren't experimenting with stuff like using a non-stiff algorithm for the stiff part of an AutoSwitch. But I suppose it's a performance optimization to avoid having to access `integrator.cache.current` for the most common cases.

**Comment by ChrisRackauckas** [comment]
Using a Newton method only makes sense for implicit methods on stiff equations. When an implicit method is used on non-stiff equations (e.g. Adams-Bashforth-Moulton), then different nonlinear solvers, such as fixed-point iteration and Anderson acceleration, are what should be used. I can't really think of a case where implicit+Newton+non-stiff makes sense, given the point of Newton is to improve the stability of the nonlinear solver.

> In general the is_stiff argument to unwrap_alg seems redundant and requires functions like dolinsolve to make assumptions about their calling context, not to mention it trusts that people aren't experimenting with nonsensical stuff like using a non-stiff algorithm for the stiff part of an AutoSwitch. But I suppose it's a performance optimization to avoid having to access integrator.cache.current for the most common cases.

It is a little rough because this is hitting type information, so you need this to have a literal to be type-stable. Accessing by `current` will not be stable. The other thing that could be done here is a manual union split.

**Comment by ChrisRackauckas** [comment]
Completed by https://github.com/SciML/OrdinaryDiffEq.jl/pull/1625
