### ISSUE TITLE
Does not compile when in use with ControlSystems and ReinforcementLearning

### ISSUE THREAD

**Issue by janstenner** [SciML/OrdinaryDiffEq.jl#1737]
I just want to report a bug we encountered:

- consider a fresh project with the very basic Project.toml:
```
[deps]
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
ReinforcementLearning = "158674fc-8238-5cab-b5ba-03dfc80d1318"
```

- Running instantiate already runs into Errors with OrdinaryDiffEq, DelayDiffEq and ControlSystems. The Error's Stacktrace is mainly:
```
ERROR: LoadError: MethodError: no method matching wrapfun_iip(::OrdinaryDiffEq.var"#lorenz#586")
Closest candidates are:
  wrapfun_iip(::Any, ::Tuple) at C:\Users\Jan\.julia\packages\DiffEqBase\S7V8q\src\utils.jl:6
Stacktrace:
 [1] (SciMLBase.ODEFunction{true, false})(f::OrdinaryDiffEq.var"#lorenz#586"; mass_matrix::LinearAlgebra.UniformScaling{Bool}, analytic::Nothing, tgrad::Nothing, jac::Nothing, jvp::Nothing, vjp::Nothing, jac_prototype::Nothing, sparsity::Nothing, Wfact::Nothing, Wfact_t::Nothing, paramjac::Nothing, syms::Nothing, indepsym::Nothing, observed::typeof(SciMLBase.DEFAULT_OBSERVED), colorvec::Nothing, sys::Nothing)
   @ SciMLBase C:\Users\Jan\.julia\packages\SciMLBase\UY87O\src\scimlfunctions.jl:1734
[...]
```

- One workaround seems to be to use ReinforcementLearning v0.9.0 which is two versions behind (and sadly that was a problem for us)

- We found another workaround by running the following:
```
add OrdinaryDiffEq@5.71.2 SciMLBase@1.47.0 DiffEqBase@6.84.0 ReinforcementLearning@0.10.1
```

This basically enforces the way it all worked back in May 2022, when FunctionWrappersWrappers wasn't in use. I guess the function wrapfun_iip was removed because FunctionWrappersWrappers made it obsolete but it's still getting called somewhere.

**Comment by ChrisRackauckas** [comment]
Your issue is that you seem to not be updating DiffEqBase so there's a missing method?

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/721
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/717
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/715

ReinforcementLearning.jl hasn't been maintained well so it's causing version nightmares. I'd just get that cleaned up.

**Comment by janstenner** [comment]
> Your issue is that you seem to not be updating DiffEqBase so there's a missing method?

actually since Julia tried to update all of DiffEqbase, SciMLBase and OrdinaryDiffEqs this Error came to life. So not updating is not the issue here.


> ReinforcementLearning.jl hasn't been maintained well so it's causing version nightmares. I'd just get that cleaned up.

It's true, ReinforcementLearning has some issues and didn't get a Release in a long time.
Just to clarify possible misunderstandings: The "we" I was talking about is not the ReinforcementLearning team. "We" are just researchers from germany working on a project that uses ReinforcementLearning and ControlSystems.

Now here's the thing:
A month back, it all worked. We just added ReinforcementLearning and ControlSystems, they both used OrdinaryDiffEqs and the other libraries and it all went well. So now that the SciML suite and OrdinaryDiffEqs got updated, it threw Errors.
Isn't the julia ecosystem designed in a way that all updates to libraries should be downwards compatible?
At least that is why I filed the issue here - to let you know.

Did I do wrong? And if yes: what would have been the right call here?

I also noticed that RL actually has frequent development happening in ther rep, they just wait for longer till they wrap it in an official release. I just tried to add them with the #master tag and precompiling did not throw any errors.
Like this:
´´´
add ReinforcementLearning#master ReinforcementLearningZoo#master ReinforcementLearningBase#master ReinforcementLearningCore#master
´´´


I guess this means that yes, an updated RL release would fix things.
But it still leaves the question open if updates in julia packages should be downwards compatible or not.

If I had published a package like OrdinaryDiffEqs, that a lot of others rely on and then released a new version that breaks some of those others, I couldn't just expect them to be updated to confirm to my new changes, right?
Or maybe I could but as far as I understand that's not the way it SHOULD be?!

**Comment by ChrisRackauckas** [comment]
This should be fixed by SciMLBase v1.52.0 not using that dispatch. Please double check.

> Actually since Julia tried to update all of DiffEqbase, SciMLBase and OrdinaryDiffEqs this Error came to life. So not updating is not the issue here.

> DiffEqBase@6.84.0 

That's not close to the latest release, v6.98.2. There was a patch in there that would have given this compatibility and such, so no it is a versioning issue. 

> I guess this means that yes, an updated RL release would fix things.
> But it still leaves the question open if updates in julia packages should be downwards compatible or not.

Sometimes, things happen and then they are fixed in patches. If you have a package that then blocks the patch fixes from being installed, 😅 well. 

Specifically, this is an intricate issue that came up as the change to allow all of DiffEq to precompile and remove the JIT lag. 

https://twitter.com/ChrisRackauckas/status/1561278092043325440

ReinforcementLearning.jl is a fairly suspect package in many ways. Its own bots are yelling at it to update:

https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/712
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/713
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/714
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/715
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/717
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/718
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/720
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/721
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/722
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/723
https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/pull/748

and it breaks Julia norms by testing with a fixed manifest (https://github.com/JuliaReinforcementLearning/ReinforcementLearning.jl/blob/master/Manifest.toml) rather than released packages. So in general, ReinforcementLearning.jl is very suspect in how it handles versioning. I fixed this anyways though.

**Comment by HenriDeh** [comment]
Hi @ChrisRackauckas, what do you mean by testing with a fixed manifest? I have merge rights for this package I might be able to change that.

**Comment by ChrisRackauckas** [comment]
Can you go through the compathelpers and get it up to latest versions? There's some core things keeping back packages like Compat, which then cause compatibility issues with almost anything else in the ecosystem.

**Comment by ChrisRackauckas** [comment]
And don't put manifests in repos: it makes tests too conservatively safe.

**Comment by HenriDeh** [comment]
It's done. The master branch has no longer a manifest and the compats are updated. I cannot make a release unfortunately because many things in the master branch are not working. This is because the main maintainer does not work much more on the project, I think because of a new job. His contributions stopped in the middle of a big overhaul but were merge into the master branch. I would fix things up if I had the time, but I have PhD and a job to do :( I can only contribute a little at a time. It may take some time (months) before a release can be done I think. 

I don't know if OP you are still interested in working with RL.jl but if you do and the master branch does not work for you, don't hesitate to open an issue and tag me to discuss what can be done. I'll help you make a PR if you need.
