### ISSUE TITLE
ERROR: LoadError: UndefVarError: `AbstractNLSolverAlgorithm` not defined

### ISSUE THREAD

**Issue by chriselrod** [SciML/OrdinaryDiffEq.jl#1811]
```julia
(p0) pkg> st -m OrdinaryDiffEq DiffEqBase
Status `~/Documents/progwork/julia/env/p0/Manifest.toml`
  [2b5f629d] DiffEqBase v6.110.0
⌃ [1dea7af3] OrdinaryDiffEq v6.20.0
Info Packages marked with ⌃ have new versions available and may be upgradable.

julia> using OrdinaryDiffEq
[ Info: Precompiling OrdinaryDiffEq [1dea7af3-3e70-54e6-95c3-0bf5283fa5ed]
ERROR: LoadError: UndefVarError: `AbstractNLSolverAlgorithm` not defined
Stacktrace:
 [1] top-level scope
   @ stdin:1
in expression starting at /home/chriselrod/.julia/packages/OrdinaryDiffEq/5B7d7/src/OrdinaryDiffEq.jl:1
```

`AbstractNLSolverAlgorithm` was removed from `DiffEqBase`, but not marked incompatible in anyway despite `OrdinaryDiffEq` depending on it.

**Comment by ChrisRackauckas** [comment]
Yes because Pkg back compats are broken, so if you mark that from DiffEqBase it will still install the wrong version (i.e. it will install versions that are outside the version bounds marked in the `[compat]` section of the Project.toml), so we stopped setting those back compats. If someone has time to update the upper bound in General that would be nice though.

**Comment by ChrisRackauckas** [comment]
Fixed by compat bounds.
